/* Generated by tools/runner/server.js on each local run. Do not edit. */
window.TESTS = {
  "suites": [
    {
      "key": "home",
      "file": "e2e/home.spec.ts",
      "label": "Home Page Tests",
      "tests": 2
    }
  ],
  "runs": {
    "home": {
      "at": "2026-08-16T17:20:46.778Z",
      "code": 0,
      "ms": 1817,
      "lines": [
        {
          "text": "",
          "tone": "text-fg",
          "ms": 513
        },
        {
          "text": "Running 2 tests using 2 workers",
          "tone": "text-fg",
          "ms": 513
        },
        {
          "text": "",
          "tone": "text-fg",
          "ms": 513
        },
        {
          "text": "  ✓  1 [chromium] › e2e/home.spec.ts:10:7 › Home Page Tests › Verify Page Loads (796ms)",
          "tone": "text-mint",
          "ms": 1769
        },
        {
          "text": "  ✓  2 [chromium] › e2e/home.spec.ts:17:7 › Home Page Tests › Verify Page Loads 2 (797ms)",
          "tone": "text-mint",
          "ms": 1771
        },
        {
          "text": "",
          "tone": "text-fg",
          "ms": 1804
        },
        {
          "text": "  2 passed (1.3s)",
          "tone": "text-mint",
          "ms": 1804
        }
      ],
      "steps": [
        {
          "phase": "begin",
          "title": "Navigate to \"./website/index.html\"",
          "category": "pw:api",
          "line": 11,
          "error": null,
          "ms": 1046
        },
        {
          "phase": "begin",
          "title": "Navigate to \"./website/index.html\"",
          "category": "pw:api",
          "line": 18,
          "error": null,
          "ms": 1048
        },
        {
          "phase": "end",
          "title": "Navigate to \"./website/index.html\"",
          "category": "pw:api",
          "line": 11,
          "error": null,
          "ms": 1376
        },
        {
          "phase": "begin",
          "title": "Expect \"toHaveTitle\"",
          "category": "expect",
          "line": 13,
          "error": null,
          "ms": 1379
        },
        {
          "phase": "end",
          "title": "Navigate to \"./website/index.html\"",
          "category": "pw:api",
          "line": 18,
          "error": null,
          "ms": 1464
        },
        {
          "phase": "begin",
          "title": "Expect \"toHaveTitle\"",
          "category": "expect",
          "line": 20,
          "error": null,
          "ms": 1492
        },
        {
          "phase": "end",
          "title": "Expect \"toHaveTitle\"",
          "category": "expect",
          "line": 13,
          "error": null,
          "ms": 1500
        },
        {
          "phase": "begin",
          "title": "Expect \"toBeVisible\" getByRole('heading', { name: 'ROI GAMBA' })",
          "category": "expect",
          "line": 14,
          "error": null,
          "ms": 1504
        },
        {
          "phase": "end",
          "title": "Expect \"toBeVisible\" getByRole('heading', { name: 'ROI GAMBA' })",
          "category": "expect",
          "line": 14,
          "error": null,
          "ms": 1517
        },
        {
          "phase": "end",
          "title": "Expect \"toHaveTitle\"",
          "category": "expect",
          "line": 20,
          "error": null,
          "ms": 1526
        },
        {
          "phase": "begin",
          "title": "Expect \"toBeVisible\" getByRole('heading', { name: 'ROI GAMBA' })",
          "category": "expect",
          "line": 21,
          "error": null,
          "ms": 1532
        },
        {
          "phase": "end",
          "title": "Expect \"toBeVisible\" getByRole('heading', { name: 'ROI GAMBA' })",
          "category": "expect",
          "line": 21,
          "error": null,
          "ms": 1543
        }
      ],
      "spec": {
        "file": "e2e/home.spec.ts",
        "lines": [
          "import { test, expect } from '@playwright/test';",
          "",
          "/**",
          " * Sample test — a starting point, not coverage.",
          " * `baseURL` is the project root (see playwright.config.ts), so relative paths",
          " * resolve against the site on disk.",
          " */",
          "",
          "test.describe('Home Page Tests', () => {",
          "  test('Verify Page Loads', async ({ page }) => {",
          "    await page.goto('./website/index.html');",
          "",
          "    await expect(page).toHaveTitle(/Roi Mark Gamba/);",
          "    await expect(page.getByRole('heading', { name: 'ROI GAMBA' })).toBeVisible();",
          "  });",
          "",
          "  test('Verify Page Loads 2', async ({ page }) => {",
          "    await page.goto('./website/index.html');",
          "",
          "    await expect(page).toHaveTitle(/Roi Mark Gamba/);",
          "    await expect(page.getByRole('heading', { name: 'ROI GAMBA' })).toBeVisible();",
          "  });",
          "})",
          ""
        ]
      }
    }
  }
};
